name: product_scanner
description: Product scanning app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.0

  # Camera
  camera: ^0.11.0
  image_picker: ^1.1.0

  # Maps
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0

  # HTTP
  http: ^1.2.0

  # State Management
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/favicon.png

  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf