name: product_scanner
description: Product scanning app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # TFLite
  flutter_tflite: ^1.0.1
  
  # Camera - downgraded to be compatible with flutter_tflite
  camera: ^0.11.0
  image_picker: ^0.8.9

  # Maps
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0

  # HTTP
  http: ^1.2.0

  # State Management
  provider: ^6.1.0

  # Local storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Image processing - downgraded to be compatible with flutter_tflite
  image: ^3.3.0  # Changed from ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/best1.tflite
    - assets/labels.txt

  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf
        