name: product_scanner
description: Product scanning app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.0

  # Environment variables
  flutter_dotenv: ^5.1.0

  # ONNX Runtime
  onnxruntime: ^1.4.1
  
  camera: ^0.10.5
  image_picker: ^1.0.7

  # Maps
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  url_launcher: ^6.2.1

  # HTTP
  http: ^1.2.0

  # State Management
  provider: ^6.1.0

  # Local storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
    - assets/best_cleaned.onnx
    - assets/labels.txt

  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
